### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by JiDarwish** [IanPorada/SIRModel#1]
I'm trying to run the project but it's static on day 0 and doesn't show progress.

**Comment by ianporada** [comment]
If you're opening the `index.html` directly with your browser, the data won't load and there will be an error similar to the following in the console:
```Access to XMLHttpRequest at 'file:///SIRModel/data/us.json' from origin 'null' has been blocked by CORS policy: Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https.```
This is due to: https://stackoverflow.com/questions/15463364/origin-null-is-not-allowed-by-access-control-allow-origin

What you can do is run `python -m SimpleHTTPServer 8888 &.` in the directory and then visit `http://localhost:8888/` to view the page correctly (https://www.oreilly.com/library/view/interactive-data-visualization/9781491921296/ch04.html).
